apiVersion: v1
kind: Service
metadata:
  name: iris-demo
  labels:
    app: iris-demo
spec:
  ports:
  - port: 8080       # 서비스 포트
    targetPort: 8080   # 타켓, 즉 pod의 포트
    protocol: TCP
    name: http
  selector:
    app: iris-demo
